services:
  - name: hrv-web-poc
    type: web
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info fontconfig
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120


